# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACkt1cZznBCXhUKKBLZ2qPhDCj9egr2D
"""

st.title('The Grades of the Probalistic class')

data= {
'Grades':[8, 12, 15, 19, 4, 4, 9.5, 10, 12, 14, 6, 6, 8],
'Students':[1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 14]
}
df = pd.DataFrame(data)

st.write("Grades:")
st.write(df)

columns = df.columns.tolist()

chart_type = st.selectbox('Select chart type', ['Bar Chart', 'Line Chart'])

st.bar_chart(df[[x_axis, y_axis]].set_index(x_axis))
elif chart_type == 'Line Chart':
st.line_chart(df[[x_axis, y_axis]].set_index(x_axis))