# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHpSIVZZpwuFcjAPbRuafuU3pKyPaBj2
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
@st.cache
def load_data():
    data = pd.read_csv('data.csv')
    return data

data = load_data()

# Title of the app
st.title("Interactive Data Visualization App")

# Display the dataset
st.subheader("Dataset Overview")
st.write(data)

# Select a column to visualize
column_to_visualize = st.selectbox("Select a column to visualize", data.columns)

# Create a simple plot
fig, ax = plt.subplots()
data[column_to_visualize].value_counts().plot(kind='bar', ax=ax)
ax.set_title(f'Distribution of {column_to_visualize}')
ax.set_xlabel(column_to_visualize)
ax.set_ylabel('Counts')

# Show the plot
st.pyplot(fig)